#数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.99.56.214/Flowable?characterEncoding=UTF-8
    username: root
    password: root

#flowable配置
#自动部署验证设置:true-开启（默认）、false-关闭
flowable:
  check-process-definitions: false